[target.xtensa-esp32s3-none-elf]
runner = "probe-rs run --chip=esp32s3 --preverify --always-print-stacktrace --no-location"

[env]
DEFMT_LOG = "info"
ESP_HAL_CONFIG_PSRAM_MODE = "octal"

[build]
rustflags = ["-C", "link-arg=-nostartfiles", "-Z", "stack-protector=all"]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
